# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 724a80c45ec9f38c4afd1a79fbf56ab9fe579e984040296bfad24a0b97a88e582c5279e6eccc3a216d824721387f75204a5fc0286bb27dcccf39789d05be6084

test:
  secret_key_base: 4e61e4c0d4abb0d094b00ac05a704955ef30735d73315242b9b88bf8b56da4d46f97ac9422119d67d5f1a4c77af2918c598e2730725a79d05c3f6d372dd0f65c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
